{
  "swagger": "2.0",
  "info": {
    "description": "Appointment server for oFrater : barber's appointment plateform.",
    "version": "1.0.0",
    "title": "oFrater API",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "name": "Nicolas MATEOS"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host": "ofrater.me",
  "basePath": "/api/v1/",
  "tags": [
    {
      "name": "in progress",
      "description": "full doc is coming"
    },
    {
      "name": "main",
      "description": "Access for visitors"
    },
    {
      "name": "user",
      "description": "Access for connected users"
    },
    {
      "name": "pro",
      "description": "Access for profesional users"
    }
  ],
  "schemes": [
    "https",
    "http"
  ],
  "paths": {
    "/main/maininputsearch": {
      "post": {
        "tags": [
          "main"
        ],
        "summary": "Search cities name by zip code or zip code by city name",
        "description": "",
        "operationId": "searchzipcity",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "input"
              ],
              "properties": {
                "input": {
                  "type": "string",
                  "example": "Roissy"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "message": {
                  "type": "string",
                  "example": "City found"
                },
                "number_result": {
                  "type": "integer",
                  "example": 2
                },
                "data": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "city": {
                        "type": "string"
                      },
                      "cp": {
                        "type": "string"
                      }
                    }
                  },
                  "example": [
                    {
                      "city": "Roissy-en-Brie",
                      "cp": "77680"
                    },
                    {
                      "city": "Roissy-en-France",
                      "cp": "95700"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/main/searchbylocation": {
      "post": {
        "tags": [
          "main"
        ],
        "summary": "Find shops by location",
        "description": "",
        "operationId": "searchbylocation",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "zipOrCity"
              ],
              "properties": {
                "zipOrCity": {
                  "type": "string",
                  "example": "94350"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "message": {
                  "type": "string",
                  "example": "Shop founded"
                },
                "number_result": {
                  "type": "integer",
                  "example": 12
                },
                "data": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "shop_name": {
                        "type": "string"
                      },
                      "opening_time": {
                        "type": "string"
                      },
                      "avatar_shop": {
                        "type": "string"
                      },
                      "is_active": {
                        "type": "boolean"
                      },
                      "address_name": {
                        "type": "string"
                      },
                      "address_number": {
                        "type": "integer"
                      },
                      "city": {
                        "type": "string"
                      },
                      "postal_code": {
                        "type": "string"
                      },
                      "geo": {
                        "type": "string"
                      },
                      "st_x": {
                        "type": "number",
                        "format": "float"
                      },
                      "st_y": {
                        "type": "number",
                        "format": "float"
                      },
                      "distance": {
                        "type": "number",
                        "format": "float"
                      }
                    }
                  },
                  "example": [
                    {
                      "id": 19,
                      "shop_name": "Papier Feuille Coupe choux",
                      "opening_time": "Du Mardi au ... De 9H00 à 19H00",
                      "avatar_shop": "https://www.url",
                      "is_active": true,
                      "address_name": "Rue Roger Salengro",
                      "address_number": 23,
                      "city": "Noisy-le-Grand",
                      "postal_code": "93160",
                      "geo": "0101000020E6100000965984622B6C484093FE5E0A0F5A0440",
                      "st_x": 48.845074,
                      "st_y": 2.543974,
                      "distance": 2003.17365389
                    },
                    {
                      "id": 17,
                      "shop_name": "Geek Barbu",
                      "opening_time": "Du Lundi au ... De 10H00 à 20H00",
                      "avatar_shop": "https://www.url",
                      "is_active": true,
                      "address_name": "Rue Georges Enesco",
                      "address_number": 6,
                      "city": "Créteil",
                      "postal_code": "94000",
                      "geo": "0101000020E6100000D8B79388F0654840118B187618930340",
                      "st_x": 48.796403,
                      "st_y": 2.446824,
                      "distance": 11846.28630894
                    },
                    "..."
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/main/shop": {
      "post": {
        "tags": [
          "main"
        ],
        "summary": "Shop details and available appointments",
        "description": "",
        "operationId": "mainShop",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "shopId": {
                  "type": "integer",
                  "example": 11
                },
                "dateStart": {
                  "type": "string",
                  "example": "2020-10-18"
                },
                "dateEnd": {
                  "type": "string",
                  "example": "2020-10-22"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "message": {
                  "type": "string",
                  "example": "Shop found"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "shop_name": {
                      "type": "string"
                    },
                    "opening_time": {
                      "type": "string"
                    },
                    "address_name": {
                      "type": "string"
                    },
                    "address_number": {
                      "type": "integer"
                    },
                    "city": {
                      "type": "string"
                    },
                    "postal_code": {
                      "type": "string"
                    },
                    "avatar_shop": {
                      "type": "string",
                      "example": ""
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid tag value"
          }
        }
      }
    },
    "/main/join": {
      "post": {
        "tags": [
          "main"
        ],
        "summary": "Register a User or a Professional User",
        "description": "",
        "operationId": "join",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "User registration must have \"role_id\": 1",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ProUser"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "message": {
                  "type": "string",
                  "example": "User (and Shop) correctly created"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "user": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer",
                          "example": 847
                        },
                        "first_name": {
                          "type": "string",
                          "example": "Ranold"
                        },
                        "last_name": {
                          "type": "string",
                          "example": "McDanold"
                        },
                        "phone_number": {
                          "type": "string",
                          "example": "0836656565"
                        },
                        "birth": {
                          "type": "string",
                          "example": "01/01/1985"
                        },
                        "mail": {
                          "type": "string",
                          "example": "ranold.md@yopmail.com"
                        },
                        "password": {
                          "type": "string",
                          "example": "$2b$10$dAvMRhhkUlkjEU1PYqX4l.AlOtufUj..."
                        },
                        "role_id": {
                          "type": "integer",
                          "example": 1
                        },
                        "is_validated": {
                          "type": "boolean",
                          "example": false
                        },
                        "account_validation_crypto": {
                          "type": "string",
                          "example": "1c837f16d360de65253c..."
                        }
                      }
                    },
                    "shop": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer",
                          "example": 63
                        },
                        "shop_name": {
                          "type": "string",
                          "example": "Mister Tiffs"
                        },
                        "opening_time": {
                          "type": "string",
                          "example": "Du Lundi au Samedi, de 08H00 à 20H00"
                        },
                        "address_name": {
                          "type": "string",
                          "example": "Rue de la Mare À Guillaume"
                        },
                        "address_number": {
                          "type": "integer",
                          "example": 12
                        },
                        "city": {
                          "type": "string",
                          "example": "Fontenay-sous-Bois"
                        },
                        "postal_code": {
                          "type": "string",
                          "example": "94120"
                        },
                        "geo": {
                          "type": "string",
                          "example": "point(48.xxxxxx 2.xxxxxx)"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid tag value"
          }
        }
      }
    },
    "/main/checkmail/{validationKey}": {
      "get": {
        "tags": [
          "main"
        ],
        "summary": "Mail Verification and password reseting route",
        "description": "",
        "operationId": "checkmail",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "validationKey",
            "in": "path",
            "description": "The key sended by mail for mail verification.",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "message": {
                  "type": "string",
                  "example": "Account validated"
                }
              }
            }
          }
        }
      }
    },
    "/main/login": {
      "post": {
        "tags": [
          "main"
        ],
        "summary": "Generate appointments in DB",
        "description": "",
        "operationId": "login",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Professional User registration must have \"role_id\": 2 and a shop object",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "mail": {
                  "type": "string",
                  "example": "ranold.md@yopmail.com"
                },
                "password": {
                  "type": "string",
                  "example": "aStr0ngP@ssw0rd"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "message": {
                  "type": "string",
                  "example": "User logged in"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer",
                      "example": 847
                    },
                    "first_name": {
                      "type": "string",
                      "example": "Ranold"
                    },
                    "last_name": {
                      "type": "string",
                      "example": "McDanold"
                    },
                    "phone_number": {
                      "type": "string",
                      "example": "0836656565"
                    },
                    "birth": {
                      "type": "string",
                      "example": "01/01/1985"
                    },
                    "mail": {
                      "type": "string",
                      "example": "ranold.md@yopmail.com"
                    },
                    "password": {
                      "type": "string",
                      "example": "$2b$10$dAvMRhhkUlkjEU1PYqX4l.AlOtufUj..."
                    },
                    "avatar": {
                      "type": "string",
                      "example": null
                    },
                    "role_id": {
                      "type": "integer",
                      "example": 2
                    },
                    "is_validated": {
                      "type": "boolean",
                      "example": true
                    },
                    "account_validation_crypto": {
                      "type": "string",
                      "example": ""
                    },
                    "owned_shop": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer",
                          "example": 63
                        },
                        "shop_name": {
                          "type": "string",
                          "example": "Mister Tiffs"
                        },
                        "opening_time": {
                          "type": "string",
                          "example": "Du Lundi au Samedi, de 08H00 à 20H00"
                        },
                        "avatar_shop": {
                          "type": "string",
                          "example": null
                        },
                        "is_active\"": {
                          "type": "boolean"
                        },
                        "address_name": {
                          "type": "string",
                          "example": "Rue de la Mare À Guillaume"
                        },
                        "address_number": {
                          "type": "integer",
                          "example": 12
                        },
                        "city": {
                          "type": "string",
                          "example": "Fontenay-sous-Bois"
                        },
                        "postal_code": {
                          "type": "string",
                          "example": "94120"
                        },
                        "geo": {
                          "type": "string",
                          "example": "0101000020E6100000E08101840F6B4..."
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/pro/profile": {
      "post": {
        "tags": [
          "pro"
        ],
        "summary": "Get Shop details for profile page in shop dashboard",
        "description": "",
        "operationId": "profilePost",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "shopId": {
                  "type": "integer",
                  "example": 63
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "message": {
                  "type": "string",
                  "example": "Shop founded"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer",
                      "example": 63
                    },
                    "shop_name": {
                      "type": "string",
                      "example": "Mister Tiffs"
                    },
                    "opening_time": {
                      "type": "string",
                      "example": "Du Lundi au Samedi, de 08H00 à 20H00"
                    },
                    "address_name": {
                      "type": "string",
                      "example": "Rue de la Mare À Guillaume"
                    },
                    "address_number": {
                      "type": "integer",
                      "example": 12
                    },
                    "city": {
                      "type": "string",
                      "example": "Fontenay-sous-Bois"
                    },
                    "postal_code": {
                      "type": "string",
                      "example": "94120"
                    },
                    "avatar_shop": {
                      "type": "string",
                      "example": null
                    },
                    "geo": {
                      "type": "string",
                      "example": "0101000020E6100000E08101840F6B4..."
                    }
                  }
                }
              }
            }
          },
          "405": {
            "description": "Invalid input"
          }
        }
      },
      "put": {
        "tags": [
          "pro"
        ],
        "summary": "Get Shop details for profile page in shop dashboard",
        "description": "",
        "operationId": "profilePut",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "shopId"
              ],
              "properties": {
                "shopId": {
                  "type": "integer",
                  "example": 63
                },
                "shop_name": {
                  "type": "string",
                  "example": "Mister Tiffs"
                },
                "opening_time": {
                  "type": "string",
                  "example": "Du Lundi au Samedi, de 08H00 à 20H00"
                },
                "address_name": {
                  "type": "string",
                  "example": "Rue de la Mare À Guillaume"
                },
                "address_number": {
                  "type": "integer",
                  "example": 12
                },
                "city": {
                  "type": "string",
                  "example": "Fontenay-sous-Bois"
                },
                "postal_code": {
                  "type": "string",
                  "example": "94120"
                },
                "avatar_shop": {
                  "type": "string",
                  "example": "https://www.🧔🪒"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "message": {
                  "type": "string",
                  "example": "Shop updated"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer",
                      "example": 63
                    },
                    "shop_name": {
                      "type": "string",
                      "example": "Mister Tiffs"
                    },
                    "opening_time": {
                      "type": "string",
                      "example": "Du Lundi au Samedi, de 08H00 à 20H00"
                    },
                    "address_name": {
                      "type": "string",
                      "example": "Rue de la Mare À Guillaume"
                    },
                    "address_number": {
                      "type": "integer",
                      "example": 12
                    },
                    "city": {
                      "type": "string",
                      "example": "Fontenay-sous-Bois"
                    },
                    "postal_code": {
                      "type": "string",
                      "example": "94120"
                    },
                    "avatar_shop": {
                      "type": "string",
                      "example": "https://www.🧔🪒"
                    },
                    "geo": {
                      "type": "string",
                      "example": "0101000020E6100000E08101840F6B4..."
                    }
                  }
                }
              }
            }
          },
          "405": {
            "description": "Invalid input"
          }
        }
      }
    },
    "/pro/createslots": {
      "post": {
        "tags": [
          "pro"
        ],
        "summary": "Generate appointments in DB",
        "description": "",
        "operationId": "createappointments",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "shopId": {
                  "type": "integer"
                },
                "dateStart": {
                  "type": "string"
                },
                "dateEnd": {
                  "type": "string"
                },
                "days": {
                  "type": "object",
                  "properties": {
                    "monday": {
                      "type": "object",
                      "properties": {
                        "amStart": {
                          "type": "string"
                        },
                        "amEnd": {
                          "type": "string"
                        },
                        "pmStart": {
                          "type": "string"
                        },
                        "pmEnd": {
                          "type": "string"
                        }
                      }
                    },
                    "tuesday": {
                      "type": "object",
                      "properties": {
                        "amStart": {
                          "type": "string"
                        },
                        "amEnd": {
                          "type": "string"
                        },
                        "pmStart": {
                          "type": "string"
                        },
                        "pmEnd": {
                          "type": "string"
                        }
                      }
                    },
                    "wednesday": {
                      "type": "object",
                      "properties": {
                        "amStart": {
                          "type": "string"
                        },
                        "amEnd": {
                          "type": "string"
                        },
                        "pmStart": {
                          "type": "string"
                        },
                        "pmEnd": {
                          "type": "string"
                        }
                      }
                    },
                    "thursday": {
                      "type": "object",
                      "properties": {
                        "amStart": {
                          "type": "string"
                        },
                        "amEnd": {
                          "type": "string"
                        },
                        "pmStart": {
                          "type": "string"
                        },
                        "pmEnd": {
                          "type": "string"
                        }
                      }
                    },
                    "friday": {
                      "type": "object",
                      "properties": {
                        "amStart": {
                          "type": "string"
                        },
                        "amEnd": {
                          "type": "string"
                        },
                        "pmStart": {
                          "type": "string"
                        },
                        "pmEnd": {
                          "type": "string"
                        }
                      }
                    },
                    "saturday": {
                      "type": "object",
                      "properties": {
                        "amStart": {
                          "type": "string"
                        },
                        "amEnd": {
                          "type": "string"
                        },
                        "pmStart": {
                          "type": "string"
                        },
                        "pmEnd": {
                          "type": "string"
                        }
                      }
                    },
                    "sunday": {
                      "type": "object",
                      "properties": {
                        "amStart": {
                          "type": "string"
                        },
                        "amEnd": {
                          "type": "string"
                        },
                        "pmStart": {
                          "type": "string"
                        },
                        "pmEnd": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              },
              "example": {
                "shopId": 63,
                "dateStart": "2020-10-18",
                "dateEnd": "2020-10-22",
                "days": {
                  "monday": {
                    "amStart": "08:00",
                    "amEnd": "09:00",
                    "pmStart": "15:00",
                    "pmEnd": "15:30"
                  },
                  "tuesday": {
                    "amStart": "08:00",
                    "amEnd": "09:00",
                    "pmStart": "15:00",
                    "pmEnd": "15:30"
                  },
                  "wednesday": {
                    "amStart": "08:00",
                    "amEnd": "09:00",
                    "pmStart": "15:00",
                    "pmEnd": "15:30"
                  },
                  "thursday": {
                    "amStart": "08:00",
                    "amEnd": "09:00",
                    "pmStart": "15:00",
                    "pmEnd": "15:30"
                  },
                  "friday": {
                    "amStart": "08:00",
                    "amEnd": "09:00",
                    "pmStart": "15:00",
                    "pmEnd": "15:30"
                  },
                  "saturday": {
                    "amStart": "09:00",
                    "amEnd": "10:00",
                    "pmStart": "",
                    "pmEnd": ""
                  },
                  "sunday": {
                    "amStart": "",
                    "amEnd": "",
                    "pmStart": "",
                    "pmEnd": ""
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "message": {
                  "type": "string",
                  "example": "Available appointment(s) correctly inserted for shopId 63"
                },
                "number_insertion": {
                  "type": "integer",
                  "example": 6
                },
                "inserted_slot": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "example": [
                    "2020-10-19 08:00",
                    "2020-10-19 08:30",
                    "2020-10-19 15:00",
                    "2020-10-22 08:00",
                    "2020-10-22 08:30",
                    "2020-10-22 15:00"
                  ]
                },
                "number_already_in_DB": {
                  "type": "integer",
                  "example": 6
                },
                "already_in_DB": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "example": [
                    "2020-10-20 08:00",
                    "2020-10-20 08:00",
                    "2020-10-20 15:00",
                    "2020-10-21 08:00",
                    "2020-10-21 08:00",
                    "2020-10-21 15:00"
                  ]
                }
              }
            }
          },
          "405": {
            "description": "Invalid input"
          }
        }
      }
    },
    "/pro/calendar": {
      "post": {
        "tags": [
          "pro"
        ],
        "summary": "Get appointments from DB for a single date or between two dates (available or not)",
        "description": "",
        "operationId": "calendar",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "shopId",
                "dateStart"
              ],
              "properties": {
                "shopId": {
                  "type": "string",
                  "example": 63
                },
                "dateStart": {
                  "type": "string",
                  "example": "2020-10-01"
                },
                "dateEnd": {
                  "type": "string",
                  "example": "2020-10-30"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "message": {
                  "type": "string",
                  "example": "Appointments correctly requested"
                },
                "number_appointment": {
                  "type": "integer",
                  "example": 4
                },
                "data": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "slot_start": {
                        "type": "string"
                      },
                      "slot_end": {
                        "type": "string"
                      },
                      "is_attended": {
                        "type": "boolean"
                      },
                      "shop_id": {
                        "type": "integer"
                      },
                      "user_id": {
                        "type": "integer"
                      },
                      "service_id": {
                        "type": "integer"
                      },
                      "first_name": {
                        "type": "string"
                      },
                      "last_name": {
                        "type": "string"
                      },
                      "phone_number": {
                        "type": "string"
                      },
                      "mail": {
                        "type": "string"
                      },
                      "avatar": {
                        "type": "string"
                      }
                    },
                    "example": [
                      {
                        "id": 421,
                        "slot_start": "2020-10-19T06:30:00.000Z",
                        "slot_end": "2020-10-19T06:59:59.000Z",
                        "is_attended": false,
                        "shop_id": 63,
                        "user_id": null,
                        "service_id": null,
                        "first_name": null,
                        "last_name": null,
                        "phone_number": null,
                        "mail": null,
                        "avatar": null
                      },
                      {
                        "id": 422,
                        "slot_start": "2020-10-19T07:00:00.000Z",
                        "slot_end": "2020-10-19T07:29:59.000Z",
                        "is_attended": false,
                        "shop_id": 63,
                        "user_id": 47,
                        "service_id": 2,
                        "first_name": "Fox",
                        "last_name": "Mulder",
                        "phone_number": "0602000000",
                        "mail": "fmulder@maybeFBI.com",
                        "avatar": "url_avatar"
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "User": {
      "type": "object",
      "properties": {
        "role_id": {
          "type": "integer",
          "example": 1
        },
        "first_name": {
          "type": "string",
          "example": "Ranold"
        },
        "last_name": {
          "type": "string",
          "example": "McDanold"
        },
        "phone_number": {
          "type": "string",
          "example": "0836656565"
        },
        "birth": {
          "type": "string",
          "example": "09/06/1988"
        },
        "mail": {
          "type": "string",
          "example": "ranold.md@yopmail.com"
        },
        "mail_confirm": {
          "type": "string",
          "example": "ranold.md@yopmail.com"
        },
        "password": {
          "type": "string",
          "example": "aStr0ngP@ssw0rd"
        },
        "password_confirm": {
          "type": "string",
          "example": "aStr0ngP@ssw0rd"
        }
      }
    },
    "ProUser": {
      "type": "object",
      "properties": {
        "role_id": {
          "type": "integer",
          "example": 2
        },
        "first_name": {
          "type": "string",
          "example": "Ranold"
        },
        "last_name": {
          "type": "string",
          "example": "McDanold"
        },
        "phone_number": {
          "type": "string",
          "example": "0836656565"
        },
        "birth": {
          "type": "string",
          "example": "09/06/1988"
        },
        "mail": {
          "type": "string",
          "example": "ranold.md@yopmail.com"
        },
        "mail_confirm": {
          "type": "string",
          "example": "ranold.md@yopmail.com"
        },
        "password": {
          "type": "string",
          "example": "aStr0ngP@ssw0rd"
        },
        "password_confirm": {
          "type": "string",
          "example": "aStr0ngP@ssw0rd"
        },
        "shop": {
          "type": "object",
          "properties": {
            "shop_name": {
              "type": "string",
              "example": "Mister Tiffs"
            },
            "opening_time": {
              "type": "string",
              "example": "Du Lundi au Samedi, de 08H00 à 20H00"
            },
            "address_name": {
              "type": "string",
              "example": "Rue de la Mare À Guillaume"
            },
            "address_number": {
              "type": "integer",
              "example": 12
            },
            "city": {
              "type": "string",
              "example": "Fontenay-sous-Bois"
            },
            "postal_code": {
              "type": "string",
              "example": "94120"
            }
          }
        }
      }
    }
  },
  "externalDocs": {
    "description": "Find out more about Swagger",
    "url": "http://swagger.io"
  }
}